### PR TITLE
Add int64 type for data unmarshaled with `UseNumber()`

### PR DESCRIPTION
**Pull request by jeffreystoke**
Hi, thank you for such great project, I really like it!

Just found a minor type issue when I was using this project along with json decoder which enabled [UseNumber](https://pkg.go.dev/encoding/json?tab=doc#Decoder.UseNumber) option, and the query results for operators `>,<,>=,<=` was not correct, this mr is an attempt to fix this, and it currently works in my use case.

Thank you for your great work!

### CODE REVIEW

**Comment by itchyny** [comment]
Adding `int64` is not a good solution here because it increases the number types and complexity. Please attach a code which you think does not work.

**Comment by jeffreystoke** [comment]
I was using json library from `k8s.io/apimachinery/pkg/util/json` which converts json numbers explicitly:

```go
func Unmarshal(data []byte, v interface{}) error {
	switch v := v.(type) {
// ...
         case *interface{}:
		// Build a decoder from the given data
		decoder := json.NewDecoder(bytes.NewBuffer(data))
		// Preserve numbers, rather than casting to float64 automatically
		decoder.UseNumber()
		// Run the decode
		if err := decoder.Decode(v); err != nil {
			return err
		}
		// If the decode succeeds, post-process the map to convert json.Number objects to int64 or float64
		return convertInterfaceNumbers(v, 0)
// ...
}

func convertInterfaceNumbers(v *interface{}, depth int) error {
	var err error
	switch v2 := (*v).(type) {
	case json.Number:
		*v, err = convertNumber(v2)
	case map[string]interface{}:
		err = convertMapNumbers(v2, depth+1)
	case []interface{}:
		err = convertSliceNumbers(v2, depth+1)
	}
	return err
}

// convertNumber converts a json.Number to an int64 or float64, or returns an error
func convertNumber(n json.Number) (interface{}, error) {
	// Attempt to convert to an int64 first
	if i, err := n.Int64(); err == nil {
		return i, nil
	}
	// Return a float64 (default json.Decode() behavior)
	// An overflow will return an error
	return n.Float64()
}
```

Here is the code to reproduce the error

```go
import (
        kubejson "k8s.io/apimachinery/pkg/util/json"
        "github.com/itchyny/gojq"
	"github.com/stretchr/testify/assert"
)

func Test_gojqError(t *testing.T) {
	const (
		input = `2`
	)

	var inputData interface{}
	err := kubejson.Unmarshal([]byte(input), inputData)
	assert.NoError(t, err)

	query, err := gojq.Parse(". > 1")
	assert.NoError(t, err)

	iter := query.Run(inputData)
	ret, ok := iter.Next()
	assert.True(t, ok)

	// will fail
	assert.True(t, ret.(bool))
}
```

And as to your performance concern, I believe the implementation of type switch is really efficient in go, and should not be a issue with so little types, so I did some benchmarks:

```text
BenchmarkTypeSwitchWithInt64-16    	74681617	        14.5 ns/op (min 14.3ns/op)
BenchmarkTypeSwitchWithoutInt64-16    	72684529	        14.7 ns/op (min 13.7ns/op)
```

and the benchmark code:

```go
func BenchmarkTypeSwitchWithInt64(b *testing.B) {
	var a interface{}

	a = int(1)
	for i := 0; i < b.N; i++ {
		switch b  := a.(type) {
		case int:
			a = int64(b)
		case int64:
			a = float64(b)
		case float64:
			a = int(b)
		}
	}
}

func BenchmarkTypeSwitchWithoutInt64(b *testing.B) {
	var a interface{}

	a = int(1)
	for i := 0; i < b.N; i++ {
		switch b  := a.(type) {
		case int:
			a = float64(b)
		case float64:
			a = int(b)
		}
	}
}
```

**Comment by itchyny** [comment]
Your test case fails with `json: Unmarshal(nil)`, seems `kubejson.Unmarshal` return some error. I don't concern the performance. Having both int and int64 looks weird. Note `gojq` [uses UseNumber option](https://github.com/itchyny/gojq/blob/8a58896f8d3543de4759a6377418a68970017cc0/cli/inputs.go#L31) and `echo 2 | gojq '. > 1'` emits `true` which is correct.

**Comment by jeffreystoke** [comment]
The test case fails due to missing `&` for `inputData`, copy paste error, following code should work

```go
func Test_gojqError(t *testing.T) {
	const (
		input = `2`
	)

	var inputData interface{}
	err := kubejson.Unmarshal([]byte(input), &inputData)
	assert.NoError(t, err)

	query, err := gojq.Parse(". > 1")
	assert.NoError(t, err)

	iter := query.Run(inputData)
	ret, ok := iter.Next()
	assert.True(t, ok)

	// will fail
	assert.True(t, ret.(bool))
}
```

and as I said in the first line of the last comment, it was caused by: explicit `json.Number` conversion:

```go
// convertNumber converts a json.Number to an int64 or float64, or returns an error
func convertNumber(n json.Number) (interface{}, error) {
	// Attempt to convert to an int64 first
	if i, err := n.Int64(); err == nil {
		return i, nil
	}
	// Return a float64 (default json.Decode() behavior)
	// An overflow will return an error
	return n.Float64()
}
```

**Comment by jeffreystoke** [comment]
looks like you have found a better way to address this issue, thank you!

**Pull request closed without merging**
