### PR TITLE
Allow use of gojq as a library

### PR DESCRIPTION
**Pull request by jmelchio**
co-authored-by: dschneider@pivotal.io

### CODE REVIEW

**Comment by itchyny** [comment]
The gojq package is actually intended to be designed to used as a library, but the cli package is not recommended to be imported. I can't ensure the compatibility of the output in the future. Can you describe your motivation to use the cli package?

**Comment by jmelchio** [comment]
> The gojq package is actually intended to be designed to used as a library, but the cli package is not recommended to be imported. I can't ensure the compatibility of the output in the future. Can you describe your motivation to use the cli package?

I didn't see an obvious spot to use it as a library. Do you have a sample of how to consume it as a library in the intended manner?

**Comment by itchyny** [comment]
Here it is (Yeah, I'm thinking of adding to README.md this weekend).
```go
package main

import (
	"fmt"
	"log"

	"github.com/itchyny/gojq"
)

func main() {
	query, err := gojq.Parse(".foo | ..")
	if err != nil {
		log.Fatalf("%s\n", err)
	}
	input := map[string]interface{}{"foo": []interface{}{1, 2, 3}}
	iter := query.Run(input)
	for {
		v, ok := iter.Next()
		if !ok {
			break
		}
		fmt.Printf("%#v\n", v)
	}
}
```

**Comment by jmelchio** [comment]
> Here it is (Yeah, I'm thinking of adding to README.md this weekend).
> 
Thanks for that. Adding that to the README.md would be good.

I'll give it a try and probably retract the pull request. 

Thanks again!

**Comment by jmelchio** [comment]
After rewriting my use of the library with the suggested use of `gojq.Parse` and `query.Run` everything is working fine. Thanks!

**Pull request closed without merging**
