### PR TITLE
Make objects with string keys const optimized

### PR DESCRIPTION
**Pull request by wader**
{a: 1} is currenty optimized but not {"a": 1}

Add makeConst query function that convert a constant value if possible.
Refactor compileObject and compileArray to use makeConst instead of peeking at generated opcodes.

### CODE REVIEW

**Comment by wader** [comment]
The reason i refactored was because i first misunderstood the code in compileObject/compileArray and for some reason assumed they would not handle nested constant values. Didn't notice they actually do until i added tests. So let me know if you want to revert that change and instead add equivalent that looks for opcodes building an object using a mix of key or string keys. But i think the code in compiler.go got a bit clearer doing it this way.

**Comment by itchyny** [comment]
Current optimization does not allocate and is efficient because the first code length check hits in most non-constant queries. But recursive constant value checking allocates too much on non-constant queries. On compiling `[[[[1,2,3,4,5,.]]]]`, it copies `[[[1,2,3,4,5]]]` and `[[1,2,3,4,5]]` and `[1,2,3,4,5]`, and `normalizeNumbers` is called 5*3 times more than it should be. Also the implementation looks much complex than checking the instructions. I think this solution is wrong for what it try to solve.

**Comment by itchyny** [comment]
Fixed.

**Comment by wader** [comment]
Ok! thanks for good example, it made it very clear why my way is not good.

**Pull request closed without merging**
