### PR TITLE
builtin: Make source jq 1.6 compatible

### PR DESCRIPTION
**Pull request by wader**
No optional if-else
$end variable causes parse error with jq

### CODE REVIEW

**Comment by wader** [comment]
Hi, i was doing some testing and wanted to verify some things with jq and noticed gojq builtin.jq had some small differences makes it incompatible with jq 1.6.

Maybe this change could be useful?

**Comment by wader** [comment]
Hmm maybe all of theses are fixed in jq master?

**Comment by wader** [comment]
Btw i noticed that `recurse/0` and `recurse/1` in builtin.jq are defined in the reverse dependency order but it seems to work anyway. Builtins are treated a bit differently?

**Comment by itchyny** [comment]
Why do I need to take care of old jq compatibility? These functions are defined for gojq.

**Comment by wader** [comment]
Understand 👍  was only if it was convenient for testing compatibility. I've been messing around with the gojq's parser so wanted to compare with jq and use large query trees

**Pull request closed without merging**
