### PR TITLE
update brew install command to use homebrew/core

### PR DESCRIPTION
**Pull request by zuisong**
Thank you for your job.

gojq has been added to homebew/core

https://github.com/Homebrew/homebrew-core/blob/master/Formula/gojq.rb

### CODE REVIEW

**Comment by itchyny** [comment]
Thanks for adding to the core Formula. But it doesn't embed the revision which I expect to see with `-h` and `-v`.

**Comment by zuisong** [comment]
```
$ gojq -v

gojq 0.12.0 (rev: HEAD/go1.16beta1)
```
Do you mean ` (rev: HEAD/go1.16beta1)`?

**Comment by itchyny** [comment]
```
 % gojq -v
gojq 0.12.0 (rev: 203d5e1/go1.14.9)
```
Also, `_gojq` is missing.

**Comment by zuisong** [comment]
**doesn't embed the revision** ,because it build from github release source code, does not have any revision info.

`_gojq`  ,   Whoops. Forgot, sorry.

**Comment by itchyny** [comment]
Maybe we can use `Utils.git_short_head`.

**Comment by itchyny** [comment]
Hmm, `Utils.git_short_head` is just an wrapper of `git` command. I give up...

**Comment by zuisong** [comment]
may be we can use  this way 
```
  url "https://github.com/minio/minio.git",
      tag:      "RELEASE.2021-01-08T21-18-21Z",
      revision: "51dad1d1301166aaf0d08a78ca67bc01f1168f42"
```
https://github.com/Homebrew/homebrew-core/blob/master/Formula/minio.rb

**Comment by zuisong** [comment]
how about this version?
```
class Gojq < Formula
  desc "Pure Go implementation of jq"
  homepage "https://github.com/itchyny/gojq"
  url "https://github.com/itchyny/gojq.git",
      tag:      "v0.12.0",
      revision: "203d5e1dfd435460500ea5b00f71eca48bf1cb88"
  version "0.12.0"
  license "MIT"

  depends_on "go" => :build

  def install
    system 'make', 'build'
    bin.install 'gojq'
    zsh_completion.install "_gojq"
  end

  test do
    assert_equal "2\n", pipe_output("#{bin}/gojq .bar", '{"foo":1, "bar":2}')
  end
end
```

```
$ gojq -v
gojq 0.12.0 (rev: 203d5e1/go1.16beta1)
```

**Comment by itchyny** [comment]
Yes, that formula works.

**Comment by zuisong** [comment]
core Formula has been updated  😊

**Comment by itchyny** [comment]
Thank you.

**Pull request merged**
